### ISSUE TITLE
Cannot read properties of undefined (reading 'runtime')

### ISSUE THREAD

**Issue by joshsmith** [aeksco/react-typescript-web-extension-starter#50]
## Prerequisites

Please answer the following questions for yourself before submitting an issue:

-   [X] I am running the latest version
-   [X] I checked the documentation and found no answer
-   [X] I checked to make sure that this issue has not already been filed
-   [X] I'm reporting the issue to the correct repository (for multi-repository projects)

## Context

Latest Chrome (Version 103.0.5060.134 (Official Build) (x86_64)), running `yarn storybook` on a fresh install.

## Expected Behavior

I expect the Popup story to render.

## Current Behavior

The mock for `browser` appears to be `undefined`

## Failure Information (for bugs)

See the logs below.

### Steps to Reproduce

1. Download this repo
2. Run `yarn install` and `yarn storybook`
3. Click on the popup in the storybook

### Failure Logs

```
Cannot read properties of undefined (reading 'runtime')
TypeError: Cannot read properties of undefined (reading 'runtime')
    at http://localhost:6007/main.iframe.bundle.js:748:67
    at invokePassiveEffectCreate (http://localhost:6007/vendors-node_modules_storybook_addon-actions_dist_esm_preset_addArgs_js-generated-config-entr-a4c2a0.iframe.bundle.js:101741:20)
    at HTMLUnknownElement.callCallback (http://localhost:6007/vendors-node_modules_storybook_addon-actions_dist_esm_preset_addArgs_js-generated-config-entr-a4c2a0.iframe.bundle.js:82204:14)
    at Object.invokeGuardedCallbackDev (http://localhost:6007/vendors-node_modules_storybook_addon-actions_dist_esm_preset_addArgs_js-generated-config-entr-a4c2a0.iframe.bundle.js:82253:16)
    at invokeGuardedCallback (http://localhost:6007/vendors-node_modules_storybook_addon-actions_dist_esm_preset_addArgs_js-generated-config-entr-a4c2a0.iframe.bundle.js:82315:31)
    at flushPassiveEffectsImpl (http://localhost:6007/vendors-node_modules_storybook_addon-actions_dist_esm_preset_addArgs_js-generated-config-entr-a4c2a0.iframe.bundle.js:101828:9)
    at unstable_runWithPriority (http://localhost:6007/vendors-node_modules_storybook_addon-actions_dist_esm_preset_addArgs_js-generated-config-entr-a4c2a0.iframe.bundle.js:110968:12)
    at runWithPriority$1 (http://localhost:6007/vendors-node_modules_storybook_addon-actions_dist_esm_preset_addArgs_js-generated-config-entr-a4c2a0.iframe.bundle.js:89535:10)
    at flushPassiveEffects (http://localhost:6007/vendors-node_modules_storybook_addon-actions_dist_esm_preset_addArgs_js-generated-config-entr-a4c2a0.iframe.bundle.js:101701:14)
    at http://localhost:6007/vendors-node_modules_storybook_addon-actions_dist_esm_preset_addArgs_js-generated-config-entr-a4c2a0.iframe.bundle.js:101578:11
```

**Comment by aeksco** [comment]
@joshsmith Thank you so much for raising this issue! I was able to replicate the problem locally and merged a fixe in PRs #52 + #53 - thanks again for taking the time to open an issue!
